flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired, InputRequired
from flask_ckeditor import CKEditorField


class PostForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = CKEditorField('Статья', validators=[DataRequired()])
    picture = FileField('Изображение (png, jpg)', validators=[FileAllowed(['png', 'jpg'])])
    submit = SubmitField('Опубликовать')


class PostUpdateForm(FlaskForm):
    title = StringField('Заголовок', validators=[DataRequired()])
    content = CKEditorField('Статья', validators=[DataRequired()])
    picture = FileField('Изображение (png, jpg)', validators=[FileAllowed(['png', 'jpg'])])
    submit = SubmitField('Опубликовать')


class CommentForm(FlaskForm):
    body = StringField('Ваш комментарий', validators=[InputRequired()])
    submit = SubmitField('Опубликовать')


class CommentUpdateForm(FlaskForm):
    body = StringField('Заголовок', validators=[DataRequired()])
    submit = SubmitField('Опубликовать')

flask_blog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required

from flask_blog import db
from flask_blog.models import Post, Comment
from flask_blog.posts.forms import PostForm, CommentForm, CommentUpdateForm
from flask_blog.posts.utils import save_picture_post

posts = Blueprint('posts', __name__)


@posts.route('/')
@posts.route('/allpost')
# @login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=posts, legend='Посты')


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.picture.data.filename:
            post = Post(title=form.title.data, content=form.content.data,
                        image_post=form.picture.data, author=current_user)

            picture_file = save_picture_post(form.picture.data)
            post.image_post = picture_file

        else:
            post = Post(title=form.title.data, content=form.content.data,
                        author=current_user)

        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.allpost'))

    image_file = url_for('static', filename=f'images/' + current_user.username + current_user.image_file)

    return render_template('create_post.html',
                           title='Новый пост',
                           form=form,
                           legend='Новый пост',
                           image_file=image_file)


@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comment = Comment.query.filter_by(post_id=post.id).order_by(db.desc(Comment.date_posted)).all()
    # db.session.commit()
    form = CommentForm()
    if request.method == 'POST' and form.validate_on_submit():
        username = current_user.username
        comment = Comment(username=username, body=form.body.data, post_id=post_id)
        db.session.add(comment)
        db.session.commit()
        flash('Комментарий к посту был добавлен', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    return render_template('post.html', title=post.title, post=post, post_id=post_id, form=form, comment=comment)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)
    form = PostForm()

    if form.validate_on_submit():
        if form.picture.data.filename:
            picture_file = save_picture_post(form.picture.data)
            post.image_post = picture_file

        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template('create_post.html', title='Обновление поста', form=form, legend='Обновление поста')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    # !!! ?
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('posts.allpost'))


@posts.route('/comment/<int:comment_id>/update/', methods=['GET', 'POST'])
@login_required
def update_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    form = CommentUpdateForm()
    # if current_user.is_admin or comment.username == current_user.username:
    if comment.username == current_user.username:
        if request.method == 'GET':
            form.body.data = comment.body
        if request.method == 'POST' and form.validate_on_submit():
            comment.body = form.body.data
            db.session.commit()
            return redirect(url_for('posts.post', post_id=comment.post_id))
    else:
        abort(403)
    return render_template('update_comment.html', form=form, title="Обновление комментария")


@posts.route('/comment/<int:comment_id>/delete/', methods=['GET', 'POST'])
@login_required
def delete_comment(comment_id):
    single_comment = Comment.query.get_or_404(comment_id)
    db.session.delete(single_comment)
    db.session.commit()
    flash('Ваш комментарий был удален!', 'success')
    return redirect(url_for('posts.post', post_id=single_comment.post_id))

flask_blog/users/routes.py
import json
from flask import render_template, url_for, flash, redirect, jsonify, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required, AnonymousUserMixin

from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flask_blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        # Временно отключить добавление новых пользователей
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана! Теперь вы можете войти в систему', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allpost'))
        else:
            flash('Войти не удалось. Пожалуйста, проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Аккаунт', image_file=image_file, form=form, posts=posts, user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('posts.allpost'))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Сброс пароля', form=form)


# @users.route('/like', methods=['POST'])
@users.route('/like/<int:post_id>/<action>')
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    return redirect(request.referrer)

    # return jsonify({
    #     'post_likes_count': post.likes.count(),
    #     'post_id': post_id,
    #     'action': action
    # })


class Anonymous(AnonymousUserMixin):
    def __init__(self):
        self.username = 'Guest'

flask_blog/templates/account.html
{% extends "layout.html" %}
{% block menu %}{% include "inc-menu.html" %}{% endblock %}
{% block content %}
    <main class="mb-5">
        <h2 class="d-flex justify-content-center mb-4">Аккаунт</h2>
        {% include "inc-flashed-messages.html" %}
        <div class="row g-3 justify-content-md-left">
            <div class="col col-lg-2">
                <img src="{{ image_file }}" class="rounded-circle" alt="Avatar Image">
            </div>
            <div class="col-md-auto">
                <h4 class="text-primary">Пользователь</h4>
                <h2>{{ current_user.username }}</h2>
                <p>{{ current_user.email }}</p>
            </div>
        </div>
        <form class="row g-3 mt-2" method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="form-group col-md-6">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group col-md-6">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group row mt-2">
                {{ form.picture.label(class="form-control-label") }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group col-12 btn-lg text-center">
                {{ form.submit(class="btn btn-outline-primary") }}
            </div>
        </form>
    </main>
{% endblock content %}
{% block bottom %}{% include "inc-bottom.html" %}{% endblock %}

flask_blog/templates/admins.html
{% extends "layout.html" %}
{% block menu %}{% include "inc-menu.html" %}{% endblock %}
{% block content %}
    <div class="container">
        <div class="content-body">
            <div class="top">
                <h2>&#128587;</h2>
            </div>
            {% include "inc-flashed-messages.html" %}
        </div>
    </div>
{% endblock content %}
{% block bottom %}{% include "inc-bottom.html" %}{% endblock %}

flask_blog/templates/inc-bottom.html
<footer class="footer fixed-bottom bg-light">
    <div class="container text-end my-2">
        <span class="text-muted">
            <small><code><a class="text-primary" href="#">@Dr0nex</a></code></small>
        </span>
    </div>
</footer>

flask_blog/templates/inc-comments.html
<form method="POST" action="{{ url_for('posts.post', post_id=post_id) }}">
    {{ form.hidden_tag() }}
    {{ form.body.label(class="form-control-label mt-3") }}
    {% if form.body.errors %}
        {{ form.body(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
            {% for error in form.body.errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% else %}
        <div class="form-group d-flex flex-column my-2">
            {{ form.body(class="form-control form-control-lg mb-3") }}
            <div class="d-flex justify-content-center">
            <input class="btn btn-outline-primary mb-4" id="submit" name="submit" type="submit"
                   value="Опубликовать">
            </div>
        </div>
    {% endif %}
</form>

{% for i in comment %}
    <div class="card w-100 mt-4 mb-4">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <a class="link-primary"
                   href="{{ url_for('users.user_posts', username=i.username) }}">{{ i.username }}</a>
                {{ i.date_posted.strftime('%d.%m.%Y-%H.%M') }}
            </div>
            <div class="row mt-3">
                <div class="col">
                    {{ i.body }}
                </div>
            </div>
            {#            <div class="row d-flex justify-content-between">#}
            {#                <div class="col-6">#}
            {#                    <div class="left_stat_side">&#128065; {{ i.views }}</div>#}
            {#                </div>#}
            {#                <div class="col-auto">#}
            {#                    <div class="right_stat_side">&#10084; {{ i.likes }}</div>#}
            {#                </div>#}
            {#            </div>#}
            <div class="row mt-3">
                {#                {% if post.author == current_user or current_user.username == i.username or current_user.is_admin %}#}
                {% if comment.username == current_user.username or current_user.username == i.username or current_user.is_admin %}
                    <div class="d-flex justify-content-between">
                    <a class="link-primary" href="{{ url_for( 'posts.update_comment', comment_id=i.id) }}"><p>Обновить
                        комментарий</p>
                    </a>
                    <a class="link-primary" href="{{ url_for( 'posts.delete_comment', comment_id=i.id) }}"><p>Удалить
                        комментарий</p>
                    </a>
                {% else %}
                    <div>
                {% endif %}
                </div>
                </div>

            </div>
        </div>
{% endfor %}

flask_blog/templates/inc-menu.html
<header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
            <img src="{{ url_for('static', filename='images/kibarium-small.png') }}" alt="kibarium">
        </a>
        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            {% if current_user.is_authenticated %}
                <a class="me-3 py-2 text-dark text-decoration-none" href="{{ url_for('posts.allpost') }}">
                [{{ current_user.username }}]</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="{{ url_for('posts.allpost') }}">Посты</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="{{ url_for('posts.new_post') }}">Новый
                    пост</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="{{ url_for('users.account') }}">Профиль</a>
                <a class="py-2 text-dark text-decoration-none" href="{{ url_for('users.logout') }}">Выйти</a>
            {% else %}
                <a class="me-3 py-2 text-dark text-decoration-none" href="{{ url_for('users.login') }}">Войти</a>
                <a class="me-3 py-2 text-dark text-decoration-none"
                   href="{{ url_for('users.register') }}">Зарегистрироваться</a>
            {% endif %}
        </nav>
    </div>
</header>

flask_blog/templates/login.html
{% extends "layout.html" %}
{% block menu %}{% include "inc-menu.html" %}{% endblock %}
{% block content %}
    <main class="mb-5">
        <h2 class="d-flex justify-content-center mb-4">Авторизация</h2>
        {% include "inc-flashed-messages.html" %}
        <div class="d-flex justify-content-center">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="row">
                    <div class="form-group col">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group col">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-group mt-2">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                    <div class="form-group col-12 mt-2 mb-2 text-center">
                        {{ form.submit(class="btn btn-outline-primary") }}
                    </div>
                    <small class="d-flex justify-content-between">
                        <div class="">
                            <a class="text-primary" href="{{ url_for('users.reset_request') }}">Забыли пароль?</a>

                        </div>
                        <div class="">
                            Нужен аккаунт?
                            <a class="text-primary"
                               href="{{ url_for('users.register') }}"> Зарегистрируйтесь</a>
                        </div>
                    </small>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}
{% block bottom %}{% include "inc-bottom.html" %}{% endblock %}

flask_blog/templates/post.html
{% extends "layout.html" %}
{% block menu %}{% include "inc-menu.html" %}{% endblock %}
{% block content %}
    <main class="mb-5">
        <h2 class="d-flex justify-content-center mb-4">{{ legend }}</h2>
        {% include "inc-flashed-messages.html" %}
        <div class="row g-3">
            <div class="col col-lg-2 d-flex flex-column mb-3 align-items-center">
                <img class="rounded-circle article-img"
                     src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <a class="link-primary"
                   href="{{ url_for('users.user_posts', username=post.author.username) }}"
                   id="author">{{ post.author.username }}</a>
            </div>
            <div class="col">
                <div class="card w-100">
                    <div class="card-body">
                        <h4 class="card-title mb-0">
                            <a class="title link-primary"
                               href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
                        </h4>
                        <div class="row">
                            <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %H:%M') }}</small>
                        </div>
                        {% if post.image_post %}
                            <div class="d-flex justify-content-center mt-3 card-img-top">
                                <img src="{{ url_for('static', filename='images/' + post.author.username + '/' + post.image_post) }}"
                                     alt="">
                            </div>
                            <hr class="mt-4">
                        {% endif %}
                        <p class="card-text mt-3">{{ post.content|safe }}</p>
                    </div>
                    {% if post.author == current_user %}
                        <div class="card-footer text-center"> {% if post.author == current_user %}
                            <a class="btn btn btn-outline-primary"
                               href="{{ url_for('posts.update_post', post_id=post.id) }}">Обновить</a>
                            <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal"
                                    data-bs-target="#deleteModal">
                                Удалить
                            </button>
                        {% endif %}
                        </div>
                    {% endif %}
                </div>
                <div class="d-flex justify-content-between align-content-around mt-3">
                    <div class="left_side_post"></div>
                    <div class="right_side_post">
                        <div class="like_buttons{{ post.id }}">
                            {% if current_user.id and current_user.has_liked_post(post) %}
                                {#                                <a href="#" class="like_button" id="unlike_{{ post.id }}">#}
                                {#                                    <img src="{{ url_for('static', filename='images/like-icon-liked-small.png') }}"#}
                                {#                                         alt="heart" width="20px">#}
                                {#                                </a>#}
                                <a href="{{ url_for('users.like_action', post_id=post.id, action='unlike') }}">
                                    <img class="like"
                                         src="{{ url_for('static', filename='images/like-icon-liked-small.png') }}"
                                         alt="heart" width="20px">
                                </a>
                            {% else %}
{#                                <a href="#" class="like_button" id="like_{{ post.id }}">#}
{#                                    <img src="{{ url_for('static', filename='images/like-icon-unliked-small.png') }}"#}
{#                                         alt="heart" width="20px">#}
{#                                </a>#}
                                <a href="{{ url_for('users.like_action', post_id=post.id, action='like') }}">
                                    <img class="unlike"
                                         src="{{ url_for('static', filename='images/like-icon-unliked-small.png') }}"
                                         alt="heart" width="20px">
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% include 'inc-comments.html' %}
            </div>
        </div>
        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Удалить пост?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрыть</button>
                        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                            <input class="btn btn-outline-danger" type="submit" value="Удалить">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}
{% block bottom %}{% include "inc-bottom.html" %}{% endblock %}

flask_blog/templates/user_posts.html
{% extends "layout.html" %}
{% block menu %}{% include "inc-menu.html" %}{% endblock %}
{% block content %}
    <main class="mb-5">
        <h2 class="d-flex justify-content-center mb-4">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h2>
        {% for post in posts.items %}
            <div class="row g-3">
                <div class="col col-lg-2 d-flex flex-column mb-3 align-items-center">
                    <img class="rounded-circle article-img"
                         src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                    <a class="link-primary"
                       href="{{ url_for('users.user_posts', username=post.author.username) }}"
                       id="author">{{ post.author.username }}</a>
                </div>
                <div class="col d-flex mb-3 align-items-center">
                    <div class="card w-100">
                        <div class="card-body">
                            <h4 class="card-title">
                                <a class="title link-primary"
                                   href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
                            </h4>
                            {% if post.image_post %}
                                <div class="d-flex justify-content-center mt-3 card-img-top">
                                    <img src="{{ url_for('static', filename='images/' + post.author.username + '/' + post.image_post) }}"
                                         alt="" width="300px">
                                </div>
                                <hr class="mt-4">
                            {% endif %}
                            <p class="card-text mt-3">{{ post.content|safe|truncate(300) }}</p>
                            <small class="card-text mt-3"><a class="title link-primary"
                                                             href="{{ url_for('posts.post', post_id=post.id) }}">Читать
                                далее...</a></small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="d-flex justify-content-center">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if posts.page == page_num %}
                        <a class="btn btn-primary mx-1 mb-4"
                           href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-primary mx-1 mb-4"
                           href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    </main>
{% endblock content %}
{% block bottom %}{% include "inc-bottom.html" %}{% endblock %}